# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true

# Minecraft
mc_version = 1.21.1
mc_version_range=[1.21.1]

# Mod Properties
mod_version = 1.0.2
mod_id = createmetallurgy
mod_name = Create Metallurgy
mod_author = Luc_Creeper74
mod_license = The MIT License (MIT)
mod_description = Create Metallurgy is an addon for Create that expands ore processing with advanced metallurgy and stylish automation systems.

# NeoForge
# https://neoforged.net/
neo_version = 21.1.219

# Registrate
registrate_version = MC1.21-1.3.0+67

# Mappings
# https://parchmentmc.org/docs/getting-started
# parchment_mc_version being set to "same" will use mc_version
# parchment_version set to "none" will disable parchment mappings
parchment_mc_version = same
parchment_version = 2024.11.17

# Create Dependencies
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6

# Others dependencies
jei_version = 19.27.0.336

jade_version = 15.10.5+neoforge

kubejs_version = 2101.7.2-build.348
createjs_version = 2101.3.1-build.18
# CurseForge file/project id
heatjs_id = 1034948
heatjs_file = 7704744