modLoader="javafml"
loaderVersion="[43,)"
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/Lucreeper74/Create-Metallurgy/issues"

[[mods]]
modId="createmetallurgy"
version="${file.jarVersion}"
displayName="Create Metallurgy"
displayURL="https://modrinth.com/mod/create-metallurgy"
logoFile="createmetallurgy.png"
#credits=""
authors="Luc_Creeper74"
description='''
Create Metallurgy is a Create Mod Addon developped by Luc_Creeper74, that allow to melt minerals wich make your ore processing factory more efficient and stylish.
'''

[[dependencies.createmetallurgy]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createmetallurgy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createmetallurgy]]
    modId="create"
    mandatory=true
    versionRange="[6.0.4,6.1.0)"
    ordering="NONE"
    side="BOTH"
