modLoader="javafml"
loaderVersion="[43,)"
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/Lucreeper74/Create-Metallurgy/issues"

[[mods]]
modId="createmetallurgy"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version="${file.jarVersion}"
displayName="Create: Metallurgy" #"${mod_name}"
displayURL="https://modrinth.com/mod/create-metallurgy"
logoFile="createmetallurgy.png"
#credits=""
authors="Luc_Creeper74"
description='''
Create Metallurgy is an addon for Create that expands ore processing with advanced metallurgy and stylish automation systems.
'''

[[dependencies.createmetallurgy]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createmetallurgy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createmetallurgy]]
    modId="create"
    mandatory=true
    versionRange="[6.0.8,6.1.0)"
    ordering="NONE"
    side="BOTH"
