modLoader="javafml"
loaderVersion="[0,)"
issueTrackerURL="https://github.com/Lucreeper74/Create-Metallurgy/issues"
license = "${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/create-metallurgy"
logoFile="createmetallurgy.png"
authors = "${mod_author}"
description = '''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

# Other optional dependencies
[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[${jei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[${jade_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[${kubejs_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs_create"
type="optional"
versionRange="[${createjs_version},)"
ordering="NONE"
side="BOTH"